// Shared between every surface that needs to show "this créateur is
// verified" so the badge reads identically everywhere -- see migration
// 0023. Only ever rendered when users.createur_verifie is true (via
// profils_publics/profils_explorables), set exclusively by
// approuver_verification(); a créateur simply requesting verification
// never turns this on. As of the current callers, that's
// CreateurProfileView's own header only -- /explorer stopped rendering
// créateur cards at all once it became a publications grid (see
// CLAUDE.md's own "Explorer becomes a publications grid" section), so
// this badge has no card-grid call site left to share with today; the
// component still lives here rather than inline in CreateurProfileView
// so a future card-style surface can reuse it without duplicating the
// gear/check geometry below.
//
// Icon-only, per a last-minute founder-approved design change: a purple
// gear ("engrenage") with a white checkmark, no adjacent "Vérifié"/
// "Verified" text. Both shapes are single, solid vectors -- no stroked
// outlines, no layered shapes -- built the same way this codebase's own
// crown logo mark is (Logo.tsx): computed once via trigonometry, then
// the resulting coordinates are pasted in as a static path/polygon,
// never recomputed at render time.
//
// GEAR: a single closed <path>, 20 teeth, generated by walking around
// the circle once -- for each tooth: a straight radial line from the
// body radius up to the tooth tip, a straight line across the flat tip,
// a straight radial line back down to the body radius, then a circular
// arc (the `A` command) along the body radius over to the next tooth's
// base. Because a tooth's two radial sides share the exact same angle
// at both the body and tip radius, they come out as true radial lines
// (not tapered/curved), matching the blocky, straight-sided teeth in the
// approved reference image. One continuous path, `fill` only, no
// `stroke` -- exactly the same "single solid shape, not an outline"
// discipline the checkmark below also follows.
//
// CHECKMARK: a single <polygon>, six vertices, built as a mitered
// constant-width stroke of a 3-point centerline (short-arm end -> elbow
// -> long-arm end) with butt caps at the two open ends and a sharp
// miter join at the elbow -- computed via perpendicular-offset/
// line-intersection vector math (never hand-picked pixel coordinates),
// which is what actually *guarantees* both arms come out the same
// width, per the brief's own explicit requirement. `fill="#ffffff"`,
// no `stroke`, so both open ends render as flat, square-cut edges (no
// `strokeLinecap: round`, no capsule look) and the elbow renders as a
// genuine sharp point, not a rounded corner.
const GEAR_PATH =
  "M 22.903 8.84 L 22.628 5.05 L 25.372 5.05 L 25.097 8.84 A 15.2 15.2 0 0 1 27.641 9.243 L 28.551 5.553 L 31.161 6.401 L 29.728 9.921 A 15.2 15.2 0 0 1 32.023 11.09 L 34.029 7.863 L 36.248 9.475 L 33.799 12.38 A 15.2 15.2 0 0 1 35.62 14.201 L 38.525 11.752 L 40.137 13.971 L 36.91 15.977 A 15.2 15.2 0 0 1 38.079 18.272 L 41.599 16.839 L 42.447 19.449 L 38.757 20.359 A 15.2 15.2 0 0 1 39.16 22.903 L 42.95 22.628 L 42.95 25.372 L 39.16 25.097 A 15.2 15.2 0 0 1 38.757 27.641 L 42.447 28.551 L 41.599 31.161 L 38.079 29.728 A 15.2 15.2 0 0 1 36.91 32.023 L 40.137 34.029 L 38.525 36.248 L 35.62 33.799 A 15.2 15.2 0 0 1 33.799 35.62 L 36.248 38.525 L 34.029 40.137 L 32.023 36.91 A 15.2 15.2 0 0 1 29.728 38.079 L 31.161 41.599 L 28.551 42.447 L 27.641 38.757 A 15.2 15.2 0 0 1 25.097 39.16 L 25.372 42.95 L 22.628 42.95 L 22.903 39.16 A 15.2 15.2 0 0 1 20.359 38.757 L 19.449 42.447 L 16.839 41.599 L 18.272 38.079 A 15.2 15.2 0 0 1 15.977 36.91 L 13.971 40.137 L 11.752 38.525 L 14.201 35.62 A 15.2 15.2 0 0 1 12.38 33.799 L 9.475 36.248 L 7.863 34.029 L 11.09 32.023 A 15.2 15.2 0 0 1 9.921 29.728 L 6.401 31.161 L 5.553 28.551 L 9.243 27.641 A 15.2 15.2 0 0 1 8.84 25.097 L 5.05 25.372 L 5.05 22.628 L 8.84 22.903 A 15.2 15.2 0 0 1 9.243 20.359 L 5.553 19.449 L 6.401 16.839 L 9.921 18.272 A 15.2 15.2 0 0 1 11.09 15.977 L 7.863 13.971 L 9.475 11.752 L 12.38 14.201 A 15.2 15.2 0 0 1 14.201 12.38 L 11.752 9.475 L 13.971 7.863 L 15.977 11.09 A 15.2 15.2 0 0 1 18.272 9.921 L 16.839 6.401 L 19.449 5.553 L 20.359 9.243 A 15.2 15.2 0 0 1 22.903 8.84 Z";

const CHECK_POINTS =
  "14.158,24.817 19.907,29.641 31.214,21.723 29.264,18.938 20.093,25.359 16.343,22.212";

// The gear body uses `currentColor` (this codebase's standard for its
// hand-made icons, see icons.tsx/navIcons.tsx) driven by a Tailwind
// text-color class, not a hardcoded hex -- so it still follows
// `--color-brand-500`'s own light/dark-mode `light-dark()` override for
// free, same as every other brand-purple element in this app.
//
// `onDark` (CreateurProfileView's header, a solid brand-gradient or an
// arbitrary uploaded cover photo) adds a small drop-shadow: a plain
// brand-purple gear can partially blend into a similarly-toned banner
// the way the old translucent pill did before it was fixed for
// DonorBadge (see that component's own "tone" comment) -- unlike that
// fix, this badge is already fully opaque, so a heavy background/ring
// treatment isn't needed, just enough shadow to keep the gear's own
// silhouette readable against a busy background. `light` (a plain card
// background) needs no such help.
const TONE_CLASSES = {
  light: "text-brand-500",
  onDark: "text-brand-500 drop-shadow-[0_1px_3px_rgba(0,0,0,0.35)]",
} as const;

export function VerifiedBadge({
  label,
  tone = "light",
  className,
}: {
  label: string;
  tone?: keyof typeof TONE_CLASSES;
  className?: string;
}) {
  return (
    <svg
      viewBox="0 0 48 48"
      role="img"
      aria-label={label}
      className={`h-6 w-6 shrink-0 ${TONE_CLASSES[tone]} ${className ?? ""}`}
    >
      <path d={GEAR_PATH} fill="currentColor" />
      <polygon points={CHECK_POINTS} fill="#ffffff" />
    </svg>
  );
}
